"""Promotion governance: PASS-gate check + paper-first strategy YAML generation.

Only a walk-forward run whose verdict is PASS is promotable.
Promotion writes ``strategies/<id>.yaml`` (paper-first, no LIVE flag) and returns
the strategy_id and yaml_path.  The caller (warehouse_routes) records the promotion
document in Mongo and flips the run's promotion_state.
"""
from __future__ import annotations

import re
from datetime import UTC, datetime
from pathlib import Path
from typing import Any


_STRATEGIES_DIR = Path("strategies")

_YAML_TEMPLATE = """\
# Auto-generated by promotion workflow on {generated_at}
# Source run: {run_id} (verdict: {verdict})
# Promote to paper only after manual review of config and risk limits.

id: {strategy_id}
class: pdp.strategies.directional_strangle.DirectionalStrangle

watchlist:
  - security_id: "13"       # NIFTY index (Dhan IDX_I)
    exchange_segment: IDX_I
    timeframes: [5m, 15m, 1h]
    indicators:
      - family: ema
        periods: [9, 20, 50]
      - family: vwap
      - family: pivots
      - family: period_levels

params:
{params_yaml}
risk:
  per_strategy_loss_cap_inr: 50000
  halt_on_cap: true

# paper-first (LIVE is NOT set — do not add it until paper validation passes)
"""


def _dict_to_yaml_block(d: dict[str, Any], indent: int = 2) -> str:
    """Minimal dict→YAML serialiser for primitive/nested values."""
    lines: list[str] = []
    pad = " " * indent
    for k, v in d.items():
        if isinstance(v, dict):
            lines.append(f"{pad}{k}:")
            lines.append(_dict_to_yaml_block(v, indent + 2))
        elif isinstance(v, (list, tuple)):
            lines.append(f"{pad}{k}:")
            for item in v:
                lines.append(f"{pad}  - {item}")
        elif isinstance(v, bool):
            lines.append(f"{pad}{k}: {'true' if v else 'false'}")
        elif v is None:
            lines.append(f"{pad}{k}: null")
        else:
            lines.append(f"{pad}{k}: {v}")
    return "\n".join(lines)


def _make_strategy_id(run_id: str, existing_ids: set[str]) -> str:
    """Derive a unique strategy_id from the run_id."""
    base = f"promoted_{run_id}"
    # Sanitise to valid identifier characters
    base = re.sub(r"[^a-zA-Z0-9_]", "_", base)[:64]
    sid = base
    n = 1
    while sid in existing_ids:
        sid = f"{base}_{n}"
        n += 1
    return sid


def promote_run(run: dict[str, Any]) -> dict[str, Any]:
    """Promote a PASS walk-forward run to a paper strategy.

    Returns dict with: strategy_id, yaml_path — or {"error": reason} on failure.
    """
    kind = run.get("kind")
    if kind != "walkforward":
        return {
            "error": f"Cannot promote run {run['run_id']!r}: kind is {kind!r}, must be "
            "'walkforward' — only walk-forward out-of-sample validated runs are promotable"
        }

    verdict = run.get("verdict")
    if verdict != "PASS":
        return {"error": f"Cannot promote run {run['run_id']!r}: verdict is {verdict!r}, must be PASS"}

    if run.get("promotion_state") == "promoted":
        return {"error": f"Run {run['run_id']!r} is already promoted"}

    # Collect existing strategy ids to avoid collision
    existing_ids: set[str] = {
        p.stem for p in _STRATEGIES_DIR.glob("*.yaml")
    }

    strategy_id = _make_strategy_id(run["run_id"], existing_ids)
    yaml_path = _STRATEGIES_DIR / f"{strategy_id}.yaml"

    config = run.get("config", {})
    params_yaml = _dict_to_yaml_block(config, indent=2)

    yaml_content = _YAML_TEMPLATE.format(
        generated_at=datetime.now(UTC).isoformat(timespec="seconds"),
        run_id=run["run_id"],
        verdict=verdict,
        strategy_id=strategy_id,
        params_yaml=params_yaml,
    )

    _STRATEGIES_DIR.mkdir(parents=True, exist_ok=True)
    yaml_path.write_text(yaml_content, encoding="utf-8")

    return {
        "strategy_id": strategy_id,
        "yaml_path": str(yaml_path),
        "run_id": run["run_id"],
        "verdict": verdict,
        "promoted_at": datetime.now(UTC).isoformat(timespec="seconds"),
    }
