"""add jobs table

Revision ID: 761f630d68d2
Revises: 0011
Create Date: 2026-06-17 09:57:49.642754

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '761f630d68d2'
down_revision: str | None = '0011'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('progress_message', sa.Text(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_backtest_daily_run_id'), table_name='backtest_daily')
    op.drop_table('backtest_daily')
    op.drop_index(op.f('ix_alerts_security_condition'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_user_status'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_backtest_runs_strategy_id'), table_name='backtest_runs')
    op.drop_table('backtest_runs')
    op.drop_index(op.f('ix_backtest_trades_run_id'), table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_index(op.f('ix_orders_placed_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_security_status'), table_name='orders')
    op.drop_index(op.f('ix_positions_security_id'), table_name='positions')
    op.alter_column('subscriptions', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_subscriptions_security_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_trades_order_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_security_id'), table_name='trades')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_trades_security_id'), 'trades', ['security_id'], unique=False)
    op.create_index(op.f('ix_trades_order_id'), 'trades', ['order_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_security_id'), 'subscriptions', ['security_id'], unique=False)
    op.alter_column('subscriptions', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_positions_security_id'), 'positions', ['security_id'], unique=False)
    op.create_index(op.f('ix_orders_security_status'), 'orders', ['security_id', 'status'], unique=False)
    op.create_index(op.f('ix_orders_placed_at'), 'orders', ['placed_at'], unique=False)
    op.create_table('backtest_trades',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('backtest_run_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entry_price', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=False),
    sa.Column('exit_price', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=False),
    sa.Column('entry_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('exit_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('realized_pnl', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=False),
    sa.Column('strategy_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('backtest_trades_pkey'))
    )
    op.create_index(op.f('ix_backtest_trades_run_id'), 'backtest_trades', ['backtest_run_id'], unique=False)
    op.create_table('backtest_runs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('from_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('to_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('start_equity', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=False),
    sa.Column('end_equity', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=False),
    sa.Column('total_trades', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('backtest_runs_pkey'))
    )
    op.create_index(op.f('ix_backtest_runs_strategy_id'), 'backtest_runs', ['strategy_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('security_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('condition', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('threshold', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('channels', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text('\'["WS"]\'::json'), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'ARMED'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('alerts_pkey')),
    sa.UniqueConstraint('user_id', 'security_id', 'condition', 'threshold', name=op.f('uq_alerts_user_sec_cond_thresh'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_alerts_user_status'), 'alerts', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_index(op.f('ix_alerts_security_condition'), 'alerts', ['security_id', 'condition'], unique=False)
    op.create_table('backtest_daily',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('backtest_run_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('starting_equity', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=False),
    sa.Column('ending_equity', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=False),
    sa.Column('daily_pnl', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=False),
    sa.Column('trades_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('max_drawdown', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=False),
    sa.Column('current_drawdown_pct', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('backtest_daily_pkey'))
    )
    op.create_index(op.f('ix_backtest_daily_run_id'), 'backtest_daily', ['backtest_run_id'], unique=False)
    op.drop_table('jobs')
    # ### end Alembic commands ###
