"""Add StrategyLeg table

Revision ID: b5706a2edae9
Revises: 0015
Create Date: 2026-07-12 19:14:40.261125

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'b5706a2edae9'
down_revision: str | None = '0015'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_legs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('security_id', sa.String(), nullable=False),
    sa.Column('leg_kind', sa.String(), nullable=False),
    sa.Column('opt_type', sa.String(), nullable=False),
    sa.Column('strike', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('expiry', sa.Date(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_legs_strategy_id'), 'strategy_legs', ['strategy_id'], unique=False)
    op.create_index('uq_strategy_leg_strategy_sid', 'strategy_legs', ['strategy_id', 'security_id'], unique=True, postgresql_where=sa.text('closed_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_strategy_leg_strategy_sid', table_name='strategy_legs', postgresql_where=sa.text('closed_at IS NULL'))
    op.drop_index(op.f('ix_strategy_legs_strategy_id'), table_name='strategy_legs')
    op.drop_table('strategy_legs')
    # ### end Alembic commands ###
