/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StrategiesRouteImport } from './routes/strategies'
import { Route as PositionalRouteImport } from './routes/positional'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as IntradayRouteImport } from './routes/intraday'
import { Route as InstrumentsRouteImport } from './routes/instruments'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as IndexRouteImport } from './routes/index'

const StrategiesRoute = StrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionalRoute = PositionalRouteImport.update({
  id: '/positional',
  path: '/positional',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const IntradayRoute = IntradayRouteImport.update({
  id: '/intraday',
  path: '/intraday',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrumentsRoute = InstrumentsRouteImport.update({
  id: '/instruments',
  path: '/instruments',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/instruments': typeof InstrumentsRoute
  '/intraday': typeof IntradayRoute
  '/portfolio': typeof PortfolioRoute
  '/positional': typeof PositionalRoute
  '/strategies': typeof StrategiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/instruments': typeof InstrumentsRoute
  '/intraday': typeof IntradayRoute
  '/portfolio': typeof PortfolioRoute
  '/positional': typeof PositionalRoute
  '/strategies': typeof StrategiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/instruments': typeof InstrumentsRoute
  '/intraday': typeof IntradayRoute
  '/portfolio': typeof PortfolioRoute
  '/positional': typeof PositionalRoute
  '/strategies': typeof StrategiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backtest'
    | '/instruments'
    | '/intraday'
    | '/portfolio'
    | '/positional'
    | '/strategies'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backtest'
    | '/instruments'
    | '/intraday'
    | '/portfolio'
    | '/positional'
    | '/strategies'
  id:
    | '__root__'
    | '/'
    | '/backtest'
    | '/instruments'
    | '/intraday'
    | '/portfolio'
    | '/positional'
    | '/strategies'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacktestRoute: typeof BacktestRoute
  InstrumentsRoute: typeof InstrumentsRoute
  IntradayRoute: typeof IntradayRoute
  PortfolioRoute: typeof PortfolioRoute
  PositionalRoute: typeof PositionalRoute
  StrategiesRoute: typeof StrategiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/strategies': {
      id: '/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof StrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positional': {
      id: '/positional'
      path: '/positional'
      fullPath: '/positional'
      preLoaderRoute: typeof PositionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intraday': {
      id: '/intraday'
      path: '/intraday'
      fullPath: '/intraday'
      preLoaderRoute: typeof IntradayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instruments': {
      id: '/instruments'
      path: '/instruments'
      fullPath: '/instruments'
      preLoaderRoute: typeof InstrumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BacktestRoute: BacktestRoute,
  InstrumentsRoute: InstrumentsRoute,
  IntradayRoute: IntradayRoute,
  PortfolioRoute: PortfolioRoute,
  PositionalRoute: PositionalRoute,
  StrategiesRoute: StrategiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
